FORMAT: 1A
HOST: https://sse.rit.edu/api/v2/

# SSE

This is the API for the Society of Software Engineers

## Group SSE API Root

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

### Retrieve the Entry Point [GET /]

+ Response 200 (application/json)
    {
        "agendaUrl": "/agenda",
        "authUrl": "/auth",
        "committeesUrl": "/committees",
        "eventsUrl": "/events",
        "headcountsUrl": "/mentoring/headcounts",
        "lingoUrl": "/lingo",
        "linksUrl": "/lings",
        "membershipsUrl": "/memberships",
        "mentorsUrl", "/mentoring/mentors",
        "officersUrl": "/officers",
        "quotesUrl": "/qdb/quotes",
        "shiftsUrl": "/mentoring/shifts",
        "specialtiesUrl": "/mentoring/specialties",
        "tagsUrl": "/qdb/tags",
        "tipsUrl": "/tips",
        "usersUrl": "/users"
    }

## Group Auth

## Refresh authentication token [PUT /auth/refresh]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 200 (application/json)
    + Attributes (Token)

+ Response 401 (application/json)
    + Attributes (Error)

## Authenticate with provider [PUT /auth/{provider}]
+ Parameters
    + provider: slack (required, enum[string]) - The provider you would like to sign in with
        + Members
            + `google` - Sign in with google
            + `slack` - Sign in with slack

+ Request (application/json)
    + Attributes (Auth)

+ Response 200 (application/json)
    + Attributes (Token)

+ Response 401 (application/json)
    + Attributes (Error)

## Group Agenda

### Agenda Collection [/agenda/{?officer}{?user}{?week}{?page}{?perPage}]

#### Get Agenda Items [GET]

+ Parameters
    + officer: 1 (optional, number) - Filter by officer ID.
    + user: knm5153 (optional, string) - Filter by user dce.
    + week: `2015-08-26` (optional, date) - Filter by week. Based on the day of the meeting
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Agenda Item]) - list of Agenda items

+ Response 200 (application/json)


#### Create an Agenda Item [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Agenda Item No User)

+ Response 201 (application/json)
    + Attributes (Agenda Item)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Agenda Item [/agenda/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of an agenda Item

#### Get an Agenda Item [GET]

+ Attributes (Agenda Item)

+ Response 200 (application/json)

#### Update an Agenda Item [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Agenda Item No User)

+ Response 200 (application/json)
    + Attributes (Agenda Item)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete an Agenda Item [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Committees

### Committees Collection [/committees/{?name}{?active}{?page}{?perPage}]

#### Get Committees [GET]

+ Parameters
    + name: Events (optional, string) - Filter by committee name
    + active: `2015-09-20` (optional, date) - Return only committees that are active on a given date
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Committee]) - list of committees

+ Response 200 (application/json)

#### Create a Committee [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Committee)

+ Response 201 (application/json)
    + Attributes (Committee)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Committee [/committees/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a committee

#### Get an Committee [GET]

+ Attributes (Committee)

+ Response 200 (application/json)

#### Update an Committee [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Committee)

+ Response 200 (application/json)
    + Attributes (Committee)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete an Committee [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Events

### Events Collection [/events/{?name}{?committee}{?location}{?before}{?after}{?featured}{?sort}{?page}{?perPage}]

#### Get Events [GET]

+ Parameters
    + name: General Meeting (optional, string) - Filter by event name
    + committee: 1 (optional, number) - Filter by committee id
    + location: SSE Lab (optional, string) - Filter by location
    + before: `2015-09-20` (optional, date) - Only return events before the specified date
    + after: `2015-09-20` (optional, date) - Only return events after the specified date
    + featured: (optional, boolean) - Only return events with an image
        + Default: `false`
    + sort: 'ASC' (optional, enum[string]) - Sorts events by start time according to the value specified
        + Members
            + `ASC` - Ascending sort
            + `DESC` - Descending sort
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Event]) - list of events

+ Response 200 (application/json)

#### Create a Event [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Event)

+ Response 201 (application/json)
    + Attributes (Event)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Event [/events/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a event

#### Get an Event [GET]

+ Attributes (Event)

+ Response 200 (application/json)

#### Update an Event [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Event)

+ Response 200 (application/json)
    + Attributes (Event)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete an Event [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Headcounts

### Headcounts Collection [/headcounts/{?count}{?greaterThan}{?lessThan}{?between}{?date}{?user}{?page}{?perPage}]

#### Get Headcounts [GET]

+ Parameters
    + count: 30 (optional, number) - Filter by count
    + greaterThan: 20 (optional, number) - Filter where count is greater than the given value
    + lessThan: 20 (optional, string) - Filter where count is less than the given value
    + between: `2015-09-20..2015-09-30` (optional, date) - Find headcounts between a given date range
    + date: `2015-09-20` (optional, date) - Only return on a specified date
    + user: 'knm5153' (optional, string) - Filter by userDce
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Headcount]) - list of headcounts

+ Response 200 (application/json)

#### Create a Headcount [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Headcount No User)

+ Response 201 (application/json)
    + Attributes (Headcount)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Headcount [/headcounts/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a headcount

#### Get a Headcount [GET]

+ Attributes (Headcount)

+ Response 200 (application/json)

#### Update a Headcount [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Headcount No User)

+ Response 200 (application/json)
    + Attributes (Headcount)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete a Headcount [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Lingo

### Lingo Collection [/lingo/{?phrase}{?search}{?approved}{?page}{?perPage}]

#### Get Lingo [GET]

+ Parameters
    + phrase: 261 (optional, number) - Filter by phrase.
    + search: class (optional, date) - Search for phrases and definitions that contain the give string
    + approved: (optional, boolean) - Returns either the unnapproved or the approved lingos
        + Default: `true`
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Lingo Approved]) - List of lingo

+ Response 200 (application/json)

+ Response 403 (application/json)
    + Attributes (Error)


#### Create a Lingo [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Lingo No Approval)

+ Response 201 (application/json)
    + Attributes (Lingo)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Lingo [/lingo/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a lingo

#### Get a Lingo [GET]

+ Attributes (Lingo Approved)

+ Response 200 (application/json)

+ Response 403 (application/json)
    + Attributes (Error)

#### Update a Lingo [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Lingo Approved)

+ Response 200 (application/json)
    + Attributes (Lingo Approved)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete a Lingo [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Links

### Links Collection [/links/{?page}{?perPage}]

#### Get Links [GET]

+ Parameters
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Link]) - List of links

+ Response 200 (application/json)

#### Create a Link [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Link)

+ Response 201 (application/json)
    + Attributes (Link)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Link [/links/{shortLink}]

+ Parameters
    + shortLink: google (required, number) - The short link of a link

#### Get a Link [GET]

+ Attributes (Link)

+ Response 200 (application/json)

#### Update a Link [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Link)

+ Response 200 (application/json)
    + Attributes (Link)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete a Link [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Memberships

### Memberships Collection [/memberships/{?phrase}{?search}{?approved}{?page}{?perPage}]

#### Get Memberships [GET]

+ Parameters
    + phrase: 261 (optional, number) - Filter by phrase.
    + search: class (optional, date) - Search for phrases and definitions that contain the give string
    + approved: (optional, boolean) - Returns either the unnapproved or the approved lingos
        + Default: `true`
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Membership Approved]) - List of memberships

+ Response 200 (application/json)

+ Response 403 (application/json)
    + Attributes (Error)


#### Create a Membership [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Membership No Approval)

+ Response 201 (application/json)
    + Attributes (Membership)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Membership [/memberships/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a membership

#### Get a Membership [GET]

+ Attributes (Membership Approved)

+ Response 200 (application/json)

+ Response 403 (application/json)
    + Attributes (Error)

#### Update a Membership [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Membership Approved)

+ Response 200 (application/json)
    + Attributes (Membership Approved)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete a Membership [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Mentors

### Mentors Collection [/mentoring/mentors/{?specialty}{?user}{?active}{?page}{?perPage}]

#### Get Mentors [GET]

+ Parameters
    + specialty: node (optional, string) - Filter by specialty
    + user: 1 (optional, number) - Filter by user dce
    + location: SSE Lab (optional, string) - Filter by location
    + active: `2015-09-20` (optional, date) - Return all mentors who were active on this date
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Mentor]) - list of mentors

+ Response 200 (application/json)

#### Create a Mentor [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Mentor)

+ Response 201 (application/json)
    + Attributes (Mentor)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Mentor [/mentoring/mentors/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a mentor

#### Get an Mentor [GET]

+ Attributes (Mentor)

+ Response 200 (application/json)

#### Update an Mentor [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Mentor)

+ Response 200 (application/json)
    + Attributes (Mentor)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete an Mentor [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Mentor Shifts

### Mentors Shifts Collection [/mentoring/shifts/{?time}{?day}{?mentor}{?active}{?page}{?perPage}]

#### Get Mentor Shifts[GET]

+ Parameters
    + time: `12:54:00` (optional, time) - Find mentors at a given time
    + day: Thursday (optional, day) - Filter by day
    + mentor: 1 (optional, number) - Filter by mentorId
    + active: `2015-09-20` (optional, date) - Return all mentor shifts that are active who were active on this date
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Mentor Shift]) - list of mentors

+ Response 200 (application/json)

#### Create a Mentor Shift [POST]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Mentor Shift)

+ Response 201 (application/json)
    + Attributes (Mentor Shift)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

### Mentor Shift [/mentoring/shifts/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of a mentor

#### Get an Mentor Shift [GET]

+ Attributes (Mentor Shift)

+ Response 200 (application/json)

#### Update an Mentor Shift [PUT]

+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]
    + Attributes (Mentor Shift)

+ Response 200 (application/json)
    + Attributes (Mentor Shift)

+ Response 422 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

#### Delete an Mentor Shift [DELETE]
+ Request (application/json)
    + Headers
        Authorization: Bearer [Your token]

+ Response 204 (application/json)

+ Response 403 (application/json)

## Group Mentor Specialties

## Group Officers

## Group QDB Quotes

## Group QDB Tags

## Group Tips

## Group Users

# Data Structures

## Auth (object)

+ secret: (required, string) - Secret associated with the auth method
+ id: knm5153 (required, string) - dce of user you are trying to log in with

## Token (object)
+ token: (required, string) - A json web token

## Pagination (object)

+ currentPage: 1 (required, number) - Current page
+ total: 1 (required, number) - Number Results overall
+ perPage: 15 (required, number) - Number requested per page

## Error (object)
+ message: (required, string) - the error message

## Agenda Item (object)

+ body: Do the thing (required, string) - Text of the agenda Item
+ week: `2015-08-26` (required, string) - Day of the officers meeting
+ officerId: 1 (required, number) - Officer Id
+ userDce: knm5153 (required, string) - User dce

## Agenda Item No User (object)

+ body: Do the thing (required, string) - Text of the agenda Item
+ week: `2015-08-26` (required, string) - Day of the officers meeting
+ officerId: 1 (required, number) - Officer Id

## Committee
+ name: Events (required, string) - Name of the committee
+ description: The events committee organizes events. (required, string) - Description of the committee

## Event
+ name: General Meeting (required, string) - Name of the event
+ startDate: `2015-08-29T14:47:56.236Z` (required, string) - The start date and time of the event
+ endDate: `2015-08-29T15:47:56.236Z` (required, string) - The end date and time of the event
+ description: This is the SSE General Meeting (optional, string)  - A description of the event
+ location: SSE Lab (required, string) - The location of the event
+ image: http://i.ytimg.com/vi/ReF6iQ7M5_A/maxresdefault.jpg (optional, string) - A URL to an image associated with the event
+ committeeId: 1 (required, number) - The committee this event is associated with

## Headcount (object)

+ count: 30 (required, number) - Number of people in the lab
+ userDce: knm5153 (required, string) - User dce

## Headcount No User (object)

+ count: 30 (required, number) - Number of people in the lab

## Lingo (object)

+ phrase: 261 (required, string) - The phrase
+ definition: a class (required, string) - the definition
+ approved: false (required, boolean) - whether or not it is approved

## Lingo Approved (object)
+ phrase: 261 (required, string) - The phrase
+ definition: a class (required, string) - the definition
+ approved: true (required, boolean) - whether or not it is approved

## Lingo No Approval (object)
+ phrase: 261 (required, string) - The phrase
+ definition: a class (required, string) - the definition

## Link (object)
+ shortLink: google (required, string) - The short link
+ longLink: https://google.com (required, string) - The url you wish to shorten

## Membership (object)
+ reason: Helping with the heist (required, string) - The reason for membership
+ userDCE: knm5153 (required, string) - The user getting membership
+ committeeId: 1 (required, number) - The committee id
+ startDate: `2015-08-22` (required, string) - The start date
+ endDate:  `2015-12-18` (required, string) - The end date
+ approved: false (required, boolean) - whether or not it is approved

## Membership Approved (object)
+ reason: Helping with the heist (required, string) - The reason for membership
+ userDCE: knm5153 (required, string) - The user getting membership
+ committeeId: 1 (required, number) - The committee id
+ startDate: `2015-08-22` (required, string) - The start date
+ endDate:  `2015-12-18` (required, string) - The end date
+ approved: true (required, boolean) - whether or not it is approved

## Membership No Approval (object)
+ reason: Helping with the heist (required, string) - The reason for membership
+ userDCE: knm5153 (required, string) - The user getting membership
+ committeeId: 1 (required, number) - The committee id
+ startDate: `2015-08-22` (required, string) - The start date
+ endDate:  `2015-12-18` (required, string) - The end date

## Mentor (object)
+ bio: I'm so cool (required, string) - the mentor bio
+ userDCE: knm5153 (required, string) - the user this mentor represents
+ startDate: `2015-08-22` (required, string) - The start date
+ endDate:  `2015-12-18` (required, string) - The end date
+ specialties: (required, array[Specialty]) - the mentors specialties

## Mentor Shift (object)
+ startTime: `12:00:00` (required, string) - the start time of the shift
+ endTime: `14:00:00` (required, string) - the start time of the shift
+ day: Thursday (required, string) - the day of the week for the mentor shift
+ mentorId: 1 (required, number) - the mentor id who has this shift

## Specialty (object)
+ name: node (required, string) - the specialty