FORMAT: 1A
HOST: http://api.sse.rit.edu/v1

# SSE

This is the API for the Society of Software Engineers

## Group SSE API Root

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

### Retrieve the Entry Point [GET /]

+ Response 200 (application/json)
    {
        "agendaUrl": "/agenda",
        "authUrl": "/auth",
        "committeesUrl": "/committees",
        "eventsUrl": "/events",
        "headcountsUrl": "/mentoring/headcounts",
        "lingoUrl": "/lingo",
        "linksUrl": "/lings",
        "membershipsUrl": "/memberships",
        "mentorsUrl", "/mentoring/mentors",
        "officersUrl": "/officers",
        "quotesUrl": "/qdb/quotes",
        "shiftsUrl": "/mentoring/shifts",
        "specialtiesUrl": "/mentoring/specialties",
        "tagsUrl": "/qdb/tags",
        "termsUrl": "/terms",
        "tipsUrl": "/tips",
        "usersUrl": "/users"
    }

## Group Agenda

Resource for officers meeting agenda items


### Agenda Collection [/agenda/{?officer}{?user}{?week}{?page}{?perPage}]


#### Get Agenda Items [GET]

+ Parameters
    + officer: 1 (optional, number) - Filter by officer ID.
    + user: knm5153 (optional, string) - Filter by user dce.
    + week: `2015-08-26` (optional, date) - Filter by week. Based on the day of the meeting
    + page: (optional, number) - Set the current page
        + Default: `1`
    + perPage: (optional, number) - Sets the number of results to return per page
        + Default: `15`

+ Attributes (Pagination)
    + data (required, array[Agenda Item]) - list of Agenda items

+ Response 200 (application/json)


#### Create an Agenda Item [POST]

+ Request (application/json)
    + Attributes (Agenda Item No User)

+ Response 201 (application/json)
    + Attributes (Agenda Item)

### Agenda Item [/agenda/{id}]

+ Parameters
    + id: 1 (required, number) - The ID of an agenda Item

#### Get an Agenda Item [GET]

+ Attributes (Agenda Item)

+ Response 200 (application/json)

#### Update an Agenda Item [PUT]

+ Request (application/json)
    + Attributes (Agenda Item No User)

+ Response 200 (application/json)
    + Attributes (Agenda Item)

#### Delete an Agenda Item [DELETE]

+ Response 204 (application/json)

## Data Structures

### Pagination (object)

+ currentPage: 1 (required, number) - Current page
+ total: 1 (required, number) - Number Results overall
+ perPage: 15 (required, number) - Number requested per page

### Agenda Item (object)

+ body: Do the thing (required, string) - Text of the agenda Item
+ week: `2015-08-26` (required, string) - Day of the officers meeting
+ officerId: 1 (required, number) - Officer Id
+ userDce: knm5153 (required, string) - User dce

### Agenda Item No User(object)

+ body: Do the thing (required, string) - Text of the agenda Item
+ week: `2015-08-26` (required, string) - Day of the officers meeting
+ officerId: 1 (required, number) - Officer Id



